baseURL = '/'
languageCode = 'en-us'
title = 'Anton Podlozny'
copyright = """Â© Anton Podlozny 2026;{{< paige/email address="anton@podlozny.com" >}}E-mail me{{< /paige/email >}}"""

[[module.imports]]
path = "github.com/willfaught/paige"

[languages.en]
weight = 10

[[languages.en.menu.main]]
identifier = "home"
name = "About me"
url = "/"
weight = 10

[[languages.en.menu.main]]
identifier = "projects"
name = "Projects"
url = "/projects/"
weight = 20

[[languages.en.menu.main]]
identifier = "events"
name = "Events"
url = "/events/"
weight = 30

[[languages.en.menu.main]]
identifier = "LinkedIn"
name = "LinkedIn ðŸ”—"
url = "https://www.linkedin.com/in/anton-podlozny/"
weight = 40

[[languages.en.menu.main]]
identifier = "GitHub"
name = "GitHub ðŸ”—"
url = "https://github.com/apodl1"
weight = 50

[markup.goldmark.renderer]
unsafe = true
